/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChatPanel: typeof import('./components/ChatPanel.vue')['default']
    ContributeComboBox: typeof import('./components/ContributeComboBox.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LLMChat: typeof import('./components/LLMChat.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    ProjectInfoContainer: typeof import('./components/ProjectInfoContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Thread: typeof import('./components/Thread.vue')['default']
  }
}
