version: '3'

services:
  app:
    container_name: civus
    build:
      context: .
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
  agent:
    container_name: newrelic-infra
    build:
      context: ./newrelic-infra
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    env_file: .env.local
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
